name: 'Build and test predicates'
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boost_version: [71, 74, 83, 84]
        gcc_version: [10, 11, 12, 13, 14]
        python_version: [3.8, 3.12]
      fail-fast: false
    env:
      CC: gcc-${{ matrix.gcc_version }}
      CXX: g++-${{ matrix.gcc_version }}
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4
      - name: Install Eigen
        run: |
          sudo apt update
          sudo apt install -yq libeigen3-dev
      - name: Install Boost
        run: |
          wget -q -O boost.tar.gz https://boostorg.jfrog.io/artifactory/main/release/1.${{ matrix.boost_version}}.0/source/boost_1_${{ matrix.boost_version }}_0.tar.gz
          mkdir boost
          tar xf boost.tar.gz -C boost --strip-components 1
          cd boost
          ./bootstrap.sh --with-libraries=math
          sudo ./b2 install
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install meson
        run: pip install meson ninja pytest jupyter nbconvert matplotlib
      - name: Build and test C++ library
        run: |
          meson setup builddir/
          meson test -C builddir/ -v
      - name: Build and test Python package
        run: |
          pip install .
          pytest test/
          jupyter nbconvert --execute --ExecutePreprocessor.kernel_name=python3 --to notebook demo/demo.ipynb
